### PR TITLE
Bump the build number

### LINKED ISSUE #1: It seems the macOS build is missing
See https://dev.azure.com/lfortran/lfortran/_build/results?buildId=278.

### PR DESCRIPTION
**Pull request by certik**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Fixes #1.

### CODE REVIEW

**Comment by certik** [comment]
@conda-forge-admin, please rerender

**Comment by certik** [comment]
I think it works now. Thanks @isuruf. Do you know what the problem was?

**Comment by isuruf** [comment]
This line, https://github.com/skvadrik/re2c/blob/master/autogen.sh#L3

**Comment by certik** [comment]
Ah, I see --- it wiped out the conda-forge files or something else needed for macOS and Linux. Thanks for noticing it!

**Comment by certik** [comment]
I tested this and it's fixed on all platforms now.

**Pull request merged**
