### PR TITLE
V1.2.1

### PR DESCRIPTION
**Pull request by certik**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by certik** [comment]
@conda-forge-admin, please rerender

**Comment by certik** [comment]
I created an upstream PR (https://github.com/skvadrik/re2c/pull/256) to include the LICENSE file in the release tarball (it's only available in git currently).

**Comment by certik** [comment]
Here are the files installed in the package:
```
├── bin
│   └── re2c
├── info
│   ├── about.json
│   ├── files
│   ├── git
│   ├── hash_input.json
│   ├── has_prefix
│   ├── index.json
│   ├── licenses
│   │   └── LICENSE
│   ├── paths.json
│   ├── recipe
│   │   ├── bld.bat
│   │   ├── build.sh
│   │   ├── conda_build_config.yaml
│   │   ├── LICENSE
│   │   ├── meta.yaml
│   │   └── meta.yaml.template
│   ├── repodata_record.json
│   └── test
│       └── run_test.sh
└── share
    ├── man
    │   └── man1
    │       └── re2c.1
    └── re2c
        └── stdlib
            └── unicode_categories.re
```

**Review by isuruf — APPROVED** [review]

**Comment by certik** [comment]
Thanks @isuruf for the review!

**Pull request merged**
